//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use rocket::serde::{Deserialize, Serialize};
use sea_orm::entity::prelude::*;

#[sea_orm::model]
#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel, Deserialize, Serialize)]
#[sea_orm(table_name = "ingredient_preps")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i32,
    pub pre_prep: Option<String>,
    pub amount: i32,
    pub unit: String,
    pub ingredient_id: i32,
    #[sea_orm(
        belongs_to,
        from = "ingredient_id",
        to = "id",
        on_update = "Cascade",
        on_delete = "Restrict"
    )]
    pub ingredients: HasOne<super::ingredients::Entity>,
    #[sea_orm(has_many, via = "recipe_ingredients")]
    pub recipes: HasMany<super::recipes::Entity>,
}

impl ActiveModelBehavior for ActiveModel {}
