//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use rocket::serde::{Deserialize, Serialize};
use sea_orm::entity::prelude::*;

#[sea_orm::model]
#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel, Deserialize, Serialize)]
#[sea_orm(table_name = "ingredients")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i32,
    pub name: String,
    #[sea_orm(has_many)]
    pub ingredient_preps: HasMany<super::ingredient_preps::Entity>,
}

impl ActiveModelBehavior for ActiveModel {}
