//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

pub mod prelude;

pub mod ingredient_preps;
pub mod ingredients;
pub mod recipe_ingredients;
pub mod recipe_tags;
pub mod recipes;
pub mod tags;
