//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

pub use super::ingredients::Entity as Ingredients;
pub use super::recipe_items::Entity as RecipeItems;
pub use super::recipe_tags::Entity as RecipeTags;
pub use super::recipes::Entity as Recipes;
pub use super::tags::Entity as Tags;
