//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

pub use super::ingredient_preps::Entity as IngredientPreps;
pub use super::ingredients::Entity as Ingredients;
pub use super::recipe_ingredients::Entity as RecipeIngredients;
pub use super::recipe_tags::Entity as RecipeTags;
pub use super::recipes::Entity as Recipes;
pub use super::tags::Entity as Tags;
