//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use sea_orm::entity::prelude::*;

#[sea_orm::model]
#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel)]
#[sea_orm(table_name = "recipe_tags")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub recipe_id: i32,
    #[sea_orm(primary_key, auto_increment = false)]
    pub tag_id: i32,
    #[sea_orm(
        belongs_to,
        from = "recipe_id",
        to = "id",
        on_update = "Cascade",
        on_delete = "Cascade"
    )]
    pub recipes: HasOne<super::recipes::Entity>,
    #[sea_orm(
        belongs_to,
        from = "tag_id",
        to = "id",
        on_update = "Cascade",
        on_delete = "Cascade"
    )]
    pub tags: HasOne<super::tags::Entity>,
}

impl ActiveModelBehavior for ActiveModel {}
