//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use sea_orm::entity::prelude::*;

#[sea_orm::model]
#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel)]
#[sea_orm(table_name = "recipe_items")]
pub struct Model {
    pub pre_prep: Option<String>,
    pub amount: i32,
    pub unit: String,
    #[sea_orm(primary_key, auto_increment = false)]
    pub recipe_id: i32,
    #[sea_orm(primary_key, auto_increment = false)]
    pub ingredient_id: i32,
    #[sea_orm(
        belongs_to,
        from = "ingredient_id",
        to = "id",
        on_update = "Cascade",
        on_delete = "Restrict"
    )]
    pub ingredients: HasOne<super::ingredients::Entity>,
    #[sea_orm(
        belongs_to,
        from = "recipe_id",
        to = "id",
        on_update = "Cascade",
        on_delete = "Cascade"
    )]
    pub recipes: HasOne<super::recipes::Entity>,
}

impl ActiveModelBehavior for ActiveModel {}
