//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use rocket::serde::{Deserialize, Serialize};
use sea_orm::entity::prelude::*;

#[sea_orm::model]
#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel, Deserialize, Serialize)]
#[sea_orm(table_name = "recipes")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i32,
    pub name: String,
    pub time: i32,
    pub difficulty: String,
    #[sea_orm(has_many, via = "recipe_ingredients")]
    pub ingredient_preps: HasMany<super::ingredient_preps::Entity>,
    #[sea_orm(has_many, via = "recipe_tags")]
    pub tags: HasMany<super::tags::Entity>,
}

impl ActiveModelBehavior for ActiveModel {}
