//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use rocket::serde::{Deserialize, Serialize};
use sea_orm::entity::prelude::*;

#[sea_orm::model]
#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel, Deserialize, Serialize)]
#[sea_orm(table_name = "recipe_ingredients")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub recipe_id: i32,
    #[sea_orm(primary_key, auto_increment = false)]
    pub ingredient_prep_id: i32,
    #[sea_orm(
        belongs_to,
        from = "ingredient_prep_id",
        to = "id",
        on_update = "Cascade",
        on_delete = "Cascade"
    )]
    pub ingredient_preps: HasOne<super::ingredient_preps::Entity>,
    #[sea_orm(
        belongs_to,
        from = "recipe_id",
        to = "id",
        on_update = "Cascade",
        on_delete = "Cascade"
    )]
    pub recipes: HasOne<super::recipes::Entity>,
}

impl ActiveModelBehavior for ActiveModel {}
