//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use rocket::futures::future::join_all;
use sea_orm::entity::prelude::*;
use rocket::serde::{Deserialize, Serialize};
use crate::entity::{ingredients, recipe_items, tags};
use crate::view::ingredient::Ingredient;
use crate::view::recipe::Recipe;
use crate::view::recipe_item::RecipeItem;
use crate::view::tag::Tag;

#[sea_orm::model]
#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel, Deserialize, Serialize)]
#[sea_orm(table_name = "recipes")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i32,
    pub name: String,
    pub time: i32,
    pub difficulty: String,
    #[sea_orm(has_many, via = "recipe_items")]
    pub ingredients: HasMany<super::ingredients::Entity>,
    #[sea_orm(has_many, via = "recipe_tags")]
    pub tags: HasMany<super::tags::Entity>,
}

impl ActiveModelBehavior for ActiveModel {}

impl Model {
    pub async fn as_view(&self, db: DatabaseConnection) -> Result<Recipe, DbErr> {
        let tags = self
            .find_related(tags::Entity)
            .all(&db)
            .await?;
        let recipe_items = recipe_items::Entity::find()
            .filter(recipe_items::COLUMN.recipe_id.eq(self.id))
            .all(&db)
            .await?;
        Ok(Recipe {
            id: self.id,
            name: self.name.clone(),
            time: self.time as u32,
            difficulty: self.difficulty.clone(),
            tags: tags.iter().map(|t| Tag {
                id: t.id,
                tag: t.tag.clone(),
            }).collect(),
            recipe_items: join_all(recipe_items.iter().map(async |ri| RecipeItem {
                pre_prep: ri.pre_prep.clone(),
                amount: ri.amount as u32,
                unit: ri.unit.clone(),
                ingredient: ri
                    .find_related(ingredients::Entity)
                    .one(&db)
                    .await
                    .unwrap()
                    .map(|i| Ingredient {
                        id: i.id,
                        name: i.name
                    })
                    .unwrap(),
            })).await
        })
    }
}
